# Nathan Gillispie Assignment 2
## 1 Pi Approximation
Compute the decimals of Pi using the Wallis formula and show the running time:

$\pi = 2\displaystyle\prod_{i=1}^\infty \frac{4i^2}{4i^2-1}$

Here $\infty$ can be replaced by a large integer number.

In [8]:
def approx_pi(n):
    product = 1.
    for i in range(1, n+1):
        product *= 4*i**2 / (4*i**2 - 1)
    return 2*product

In [17]:
n = int(1e6)
%time p = approx_pi(n)
print("\nπ ≈ %.8f with %d iterations"%(p,n))

CPU times: user 246 ms, sys: 0 ns, total: 246 ms
Wall time: 231 ms

π ≈ 3.14159187 with 1000000 iterations


## 2 Fibbonacci
Write a function that displays the n first terms of the Fibonacci sequence, defined by: \begin{cases} U_0 = 0\\ U_1 = 1\\ U_{n+2} = U_{n+1} + U_n \end{cases}



In [113]:
def fib(n: int) -> list:
    fib = [0,1]
    for i in range(n-2):
        fib.append(fib[i] + fib[i+1])
    return fib
print(fib(20))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]


## 3 `__lt__` and `__eq__`
The following are the atomic numbers of lithium, carbon, and sodium. Assign each to a variable and use Python Boolean logic operators to evaluate each of the following.

Li, C, Na = 3, 6, 11

1. Is Li greater than C?
2. Is Na less than or equal to C?
3. Is either Li or Na greater than C?
4. Are both C and Na greater than Li?

In [11]:
Li, C, Na = 3, 6, 11

In [14]:
Li > C

False

In [15]:
Na <= C

False

In [17]:
(Li > C) | (Na > C)

True

In [18]:
(C > Li) & (Na > Li)

True

## 4 DNA
DNA is composed of two strands of the nucleotides adenine (A), thymine (T), guanine (G), and cytosine (C). The two strands are lined up with adenine always opposite of thymine and guanine opposite cytosine. For example, if one strand is ATGGC, then the opposite strand is TACCG. Write a function that takes in a DNA strand as a string and prints the opposite DNA strand of nucleotides.

In [31]:
def DNA_flip(seq):
    seq = seq.upper() 
    alt = ""
    for letter in seq:
        match letter:
            case "A":
                alt += "T"
            case "T":
                alt += "A"
            case "G":
                alt += "C"
            case "C":
                alt += "G"
            case _:
                print("Not DNA sequence")
                return None
    return alt
    
DNA_flip("atggc")

'TACCG'

# 5 reaction rate
Complete a function started below that calculates the rate of a single-step chemical reaction nA → P using the differential rate law (Rate = k[A]$^n$).

In [54]:
def rate(A0, k=1.0, n=1):
    ''' (concentration(M), k = 1.0, n = 1) → rate (M/s)
    Takes in the concentration of A (M), the rate constant (k), 
    and the order (n) and returns the rate (M/s)
    '''
    return k * A0 ** n

In [55]:
rate(.001)

0.001

# 6 `xyz` file and dist
Save the information below about a water molecule in a text file. Use the np.genfromtxt() method to read the atom xyz coordinates, and then calculate the atom-atom distance between each atom pair using a distance calculation function (you need to define this function).


In [56]:
import numpy as np

In [108]:
water_xyz = """3
Water xyz file
O        0.000000     -0.007156      0.965491
H1      -0.000000      0.001486     -0.003471
H2       0.000000      0.931026      1.207929"""

water_xyz = water_xyz.split("\n")
print(mol := np.genfromtxt(water_xyz, skip_header=2, usecols=(1,2,3)))

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [110]:
def get_dist(mol):
    natoms = len(mol)
    for i in range(natoms):
        atom1 = mol[i]
        for j in range(i + 1, natoms):
            atom2 = mol[j]
            dist = np.sqrt(np.sum((atom2 - atom1)**2))
            print("distance atom%d to atom%d = %f"%(i+1,j+1,dist))

get_dist(mol)

distance atom1 to atom2 = 0.969001
distance atom1 to atom3 = 0.969000
distance atom2 to atom3 = 1.526936


# 7 `numpy` operations
Generate an array containing integers 0 $\rightarrow$ 14 (inclusive).
1. Reshape the array to be a 3 $\times$ 5 array.
2. Transpose the array, so now it should be a 5 $\times$ 3 array.
3. Make the array one-dimensional again without using the reshape() method.

In [81]:
print(arr := np.arange(15))
print('\n1. ',arr := arr.reshape((3,5)))
print('\n2. ',arr := arr.transpose())
print('\n3. ',arr := arr.reshape((15)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

1.  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

2.  [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

3.  [ 0  5 10  1  6 11  2  7 12  3  8 13  4  9 14]


# 8 more `numpy` operations
Generate a two-dimensional array with the following code.

`arr2 = np.random.randint(0, high=10, size=15).reshape(5, 3)`
1. Index the second element of the third column.
2. Slice the array to get the entire third row.
3. Slice the array to access the entire first column.
4. Slice the array to get the last two elements of the first row.

In [96]:
arr2 = np.random.randint(0, high=10, size=15).reshape(5, 3)
print(arr2)
print("\n1. ", arr2[2,1])
print("2. ", arr2[2])
print("3. ", arr2[:,0])
print("4. ", arr2[0,-2:])

[[1 6 2]
 [2 8 1]
 [3 3 6]
 [7 6 3]
 [8 2 7]]

1.  3
2.  [3 3 6]
3.  [1 2 3 7 8]
4.  [6 2]
